// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import com.codeborne.selenide.Configuration;
import com.codeborne.selenide.WebDriverRunner;
import static com.codeborne.selenide.Selectors.*;
import static com.codeborne.selenide.Condition.*;
import static com.codeborne.selenide.Selenide.*;
import static org.junit.jupiter.api.Assertions.*;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.Keys;
import java.util.*;
public class TestSeleniumTest {
  private Map<String, Object> vars;
  @BeforeEach
  public void setUp() {
    Configuration.browser = "chrome";
    vars = new HashMap<>();
  }
  @AfterEach
  public void tearDown() {
  }
  @Test
  public void testSelenium() {
    open("https://demoqa.com/");
    WebDriverRunner.getWebDriver().manage().window().setSize(new Dimension(1280, 713));
    $(".card:nth-child(2) svg").click();
    $(".show .text").click();
    $("#firstName").click();
    $("#firstName").val("Alex");
    $("#lastName").click();
    $("#lastName").val("TovStol");
    $("#userEmail").click();
    $("#userEmail").val("alex@mail.ru");
    $(".custom-radio:nth-child(1) > .custom-control-label").click();
    $("#userNumber").click();
    $("#userNumber").val("9875995990");
    $("#dateOfBirthInput").click();
    $(".react-datepicker__month-select").click();
    $(".react-datepicker__month-select").selectOption("July");
    $(".react-datepicker__day-names").click();
    $(".react-datepicker__year-select").click();
    $(".react-datepicker__year-select").selectOption("2015");
    $(".react-datepicker__day--001:nth-child(4)").click();
    $(".custom-checkbox:nth-child(1) > .custom-control-label").click();
    $(".subjects-auto-complete__value-container").click();
    $("#subjectsInput").val("Ma");
    $("#subjectsInput").sendKeys(Keys.ENTER);
    $("#subjectsInput").val("C");
    $("#subjectsInput").sendKeys(Keys.ENTER);
    $("#uploadPicture").click();
    $("#uploadPicture").click();
    $("#uploadPicture").click();
    $("#uploadPicture").click();
    $("#currentAddress").click();
    $(".css-1pahdxg-control > .css-1hwfws3").click();
    $("#uploadPicture").val("C:\\fakepath\\1.png");
    $(".css-1pahdxg-control > .css-1hwfws3").click();
    $("#react-select-3-option-1").click();
    $(".css-1wa3eu0-placeholder").click();
    $("#react-select-4-option-1").click();
    $("#submit").click();
    actions().moveToElement($("#submit")).perform();
    actions().moveToElement($(byTagName("body")), 0, 0).perform();
    $("#example-modal-sizes-title-lg").shouldHave(text("Thanks for submitting the form"));
    $("#closeLargeModal").click();
  }
}
